# Generated by Django 5.0.3 on 2024-04-03 21:44

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=onboarding.models.generate_account_id, max_length=12, unique=True),
        ),
    ]
