# Generated by Django 5.0.3 on 2024-04-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_user_otp_code_user_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification',
            field=models.CharField(default='unverified', max_length=255),
        ),
    ]
