# Generated by Django 5.0.3 on 2024-04-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_user_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
