# Generated by Django 5.0.3 on 2024-04-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_paymentlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlink',
            name='link',
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='crypto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='tag_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='wallet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
