# Generated by Django 5.0.3 on 2024-04-18 19:59

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_remove_paymentlink_link_paymentlink_crypto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='link_id',
            field=models.CharField(default=onboarding.models.generate_account_id, max_length=20, unique=True),
        ),
    ]
