# Generated by Django 5.0.3 on 2024-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_alter_paymentlink_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='link_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
