# Generated by Django 5.0.3 on 2024-04-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_alter_paymentlink_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='qr_code_image',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
