# Generated by Django 5.0.3 on 2024-05-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0016_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='success_url',
            field=models.URLField(null=True),
        ),
    ]
