# Generated by Django 5.0.3 on 2024-05-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0017_payments_success_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='crypto_network',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
