# Generated by Django 5.0.3 on 2024-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0018_payments_business_name_payments_crypto_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
