# Generated by Django 5.0.3 on 2024-05-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0019_payments_transaction_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='item',
        ),
    ]
