# Generated by Django 5.0.3 on 2024-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0021_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_url',
            field=models.URLField(null=True),
        ),
    ]
