# Generated by Django 5.0.3 on 2024-05-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0022_invoice_invoice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.paymentlink'),
        ),
    ]
