# Generated by Django 5.0.3 on 2024-05-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0023_alter_invoice_payment_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
