# Generated by Django 5.0.3 on 2024-05-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0024_rename_payments_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='wallet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
