# Generated by Django 5.0.3 on 2024-05-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0031_alter_paymentlink_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='wallet',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
    ]
