# Generated by Django 5.0.3 on 2024-05-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0032_alter_paymentlink_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlink',
            name='wallet',
        ),
    ]
