# Generated by Django 5.0.3 on 2024-05-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0034_remove_paymentlink_crypto_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='wallets',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
