# Generated by Django 5.0.3 on 2024-05-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0036_remove_paymentlink_wallets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlink',
            name='qr_code_image',
        ),
        migrations.AddField(
            model_name='wallet',
            name='qr_code_image',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
