# Generated by Django 5.0.3 on 2024-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0037_remove_paymentlink_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
