# Generated by Django 5.0.3 on 2024-05-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0038_payment_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='api_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
