# Generated by Django 5.0.3 on 2024-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0039_payment_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
