# Generated by Django 5.0.3 on 2024-05-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0040_paymentlink_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='store_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
