# Generated by Django 5.0.3 on 2024-05-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0042_payment_converted_amount_payment_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
