# Generated by Django 5.0.3 on 2024-05-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0045_alter_payment_converted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='link_logo',
            field=models.FileField(blank=True, null=True, upload_to='link_logos'),
        ),
    ]
