# Generated by Django 5.0.3 on 2024-05-16 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0046_paymentlink_link_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('token_logo', models.FileField(blank=True, null=True, upload_to='link_logos')),
                ('token_name', models.CharField(blank=True, max_length=200, null=True)),
                ('token_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
