# Generated by Django 5.0.3 on 2024-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0048_alter_token_token_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='payment_link',
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
