# Generated by Django 5.0.3 on 2024-05-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0049_remove_wallet_payment_link_wallet_wallet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentlink',
            old_name='store_description',
            new_name='link_description',
        ),
    ]
