# Generated by Django 5.0.3 on 2024-05-19 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0052_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.paymentlink'),
        ),
    ]
