# Generated by Django 5.0.3 on 2024-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0053_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
