# Generated by Django 5.0.3 on 2024-05-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0054_paymentlink_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='link_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='link_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='link_user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
