# Generated by Django 5.0.3 on 2024-05-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0055_payment_customer_country_payment_customer_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer_ip',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer_name',
            new_name='user_agent',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_user_agent',
        ),
    ]
