# Generated by Django 5.0.3 on 2024-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0056_rename_customer_country_payment_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='qr_code_image',
            field=models.CharField(max_length=200),
        ),
    ]
