# Generated by Django 5.0.3 on 2024-05-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0057_alter_wallet_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='qr_code_image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
