# Generated by Django 5.0.3 on 2024-05-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0058_alter_wallet_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='random_added_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='qr_code_image',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
