# Generated by Django 5.0.3 on 2024-05-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0059_payment_random_added_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='find_tx_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
