# Generated by Django 5.0.3 on 2024-05-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0060_payment_find_tx_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
