# Generated by Django 5.0.3 on 2024-05-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0061_payment_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='success_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
