# Generated by Django 5.0.3 on 2024-06-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0062_alter_payment_success_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
