# Generated by Django 5.0.3 on 2024-06-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0063_payment_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
