# Generated by Django 5.0.3 on 2024-06-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0065_remove_paymentlink_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='access_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
